### ISSUE TITLE
downloading with PIP

### ISSUE THREAD

**Issue by gunstonej** [buds-lab/the-building-data-genome-project#2]
Hi there, 

I'm relatively new at cloning packages from GitHub. I'm try to download this package using pip, i've followed advice from here: 
https://stackoverflow.com/questions/15268953/how-to-install-python-package-from-github 
and here: 
https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

with command: 
pip install -e git+https://github.com/buds-lab/the-building-data-genome-project.git

but go the following error: 
could not detect requirement name, please specify one with #egg=

could any suggest what is causing the issue / a solution? 

cheers

**Comment by daren-thomas** [comment]
@gunstonej that is because this isn't actually a package. for the repository to be a package, as far as I understand it, it should have a `setup.py` file in the root folder. instead, just use git to clone it - or the GitHub Desktop tool.

@cmiller8 maybe you could look into making this a package and publishing it on PyPI? I'll gladly talk you through some points next week...

**Comment by cmiller8** [comment]
@gunstonej -- Daren is right. At this point, the repository is based on downloading a .csv file and manipulating it using Python or R (or anything else for that matter). Examples of doing this can be found in the Jupyter notebooks in the repository. 

Making it an installable Python package might come in the future - but only if we start making custom Python functions and objects to process the data.
